wandb_version: 1

epochs:
  desc: null
  value: 10
_wandb:
  desc: null
  value:
    code_path: code/train.py
    python_version: 3.9.12
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1685029529.366553
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.15.3
      8:
      - 2
      - 5
