wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    code_path: code/train.py
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.12
    start_time: 1685029504.204009
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.12
      5: 0.13.9
      8:
      - 2
      - 5
epochs:
  desc: null
  value: 10
